server.port=8084
spring.application.name=meal-service

# Database Configuration (Meal Service DB)
spring.datasource.url=jdbc:postgresql://localhost:5436/meal_db
spring.datasource.username=meal_user
spring.datasource.password=meal_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.healthfit.meal=DEBUG
