server.port=8083
spring.application.name=fitness-service

# Database Configuration (Fitness Service DB)
spring.datasource.url=jdbc:postgresql://localhost:5435/fitness_db
spring.datasource.username=fitness_user
spring.datasource.password=fitness_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.healthfit.fitness=DEBUG
