spring.application.name=student-service

# Server Configuration
server.port=8083

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5435/student_db
spring.datasource.username=postgres
spring.datasource.password=sa123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/openapi.json
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# JWT Configuration (same as AUTH-SERVICE for validation)
spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=86400000

# Security Logging
logging.level.org.springframework.security=INFO
logging.level.com.soa.student.security=DEBUG

# Actuator endpoints for health checks
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
