server.port=8082
spring.application.name=user-service

# Database Configuration (User Service DB)
spring.datasource.url=jdbc:postgresql://localhost:5434/user_db
spring.datasource.username=user_user
spring.datasource.password=user_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.healthfit.user=DEBUG
